apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-blue
spec:
  selector:
    matchLabels:
      app: example-app
      environment: blue
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
        environment: blue
    spec:
      containers:
      - name: tokio-blue
        image: lawless/example-app:1.0
        imagePullPolicy: Never
        env:
        - name: APP_COLOR
          value: "blue"
        resources:
          limits:
            memory: "128Mi"
            cpu: "25"
          requests:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 80
