apiVersion: apps/v1
kind: Deployment
metadata:
  name: tokio-green
spec:
  selector:
    matchLabels:
      app: example-app
      environment: green
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
        environment: green
    spec:
      containers:
      - name: demoapp-green
        image: lawless92/example-app:1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: APP_COLOR
          value: "green"
        resources:
          limits:
            memory: "128Mi"
            cpu: "25m"
          requests:
            memory: "64Mi"
            cpu: "10m"
        ports:
        - containerPort: 80